version: '3.9'

services:
  postgres:
    container_name: bgdb_postgres
    restart: always
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=bgdb_user
      - POSTGRES_DB=bgdb_db
    networks:
      - bgdb-network
  web:
    container_name: bgdb_web
    restart: always
    build: .
    links:
      - postgres
    networks:
      - bgdb-network
  nginx:
    container_name: bgdb_nginx
    restart: always
    image: nginx:latest
    volumes:
      - ./web/conf/proxy_settings.conf:/etc/nginx/conf.d/proxy_settings.conf
      - ./web/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/conf/allein.xyz.key:/etc/nginx/cert/allein.xyz.key
      - ./web/conf/allein.xyz.pem:/etc/nginx/cert/allein.xyz.pem
    ports:
      - "80:80"
      - "443:443"
    networks:
      - bgdb-network

networks:
  bgdb-network: